### ISSUE TITLE
remove dependence on git access

### ISSUE THREAD

**Issue by allonw** [YosefLab/Compass#19]
Tom:

the crux of the problem could be that the package is using git to produce the version of the package in the log file. Unfortunately, given the node that has the job cannot access git or the internet (peculiarities of oxford - apparently security concerns), this causes issues.

Commenting out lines 204-212 in compass/main.py (i.. the section below) has managed to get it running.

try:

commit 
= sp.check_output(

["git",
'--git-dir',
globals.GIT_DIR,
"rev-parse",
"--short",

"HEAD"],

stderr=open(os.devnull,
'w')

)

logger.debug("Git commit: "
+
commit.decode())

except
sp.CalledProcessError:

logger.debug("Git commit: Not in Git repo")

If there are users with similar architecture to Oxford whereby the job nodes have no access to git or the internet, those users will likely want to use this fix.

**Comment by crichgriffin** [comment]
I helped Tom debug this issue on our servers.

To be specific, the root of this issue is that git is not installed on the cluster nodes.
sp.check_output returns a FileNotFound error in the event that git is not installed, so adding an additional Exception to lines 204-212 in main.py to catch it would fix it.
Something like: 
```
try:
    sp.check_output(["git", "--git-dir", globals.GIT_DIR, "rev-parse", "--short", "HEAD"],
                                  stderr=open(os.devnull, 'w'))
    logger.debug("Git commit: " = commit.decode())
except FileNotFoundError:
    logger.debug("FileNotFoundError may indicate that git is not installed")
    pass
except sp.CalledProcessError:
    logger.debug("Git commit: No in Git repo")
```

I could put it in a pull request, but it didn't seem quite worth it for 3 lines.

All the best,
Charlotte

**Comment by DPLemonade** [comment]
Marking as resolved
