### ISSUE TITLE
Tips for running thousands of cells

### ISSUE THREAD

**Issue by nathanin** [YosefLab/Compass#21]
Hi, We are interested in using Compass to evaluate metabolic activity in our 10X data. 

Noticing that the method was tested with ~hundreds of cells, we have run initial tests by sampling 100 cells and found good results in ~8 hours run time on 10 cores. To expedite things, we would like to partition groups of cells to run in separate jobs in a cluster environment. I have noticed the default value for information sharing between cells (`--lambda`) is `0`, does this mean that a fully parallelized run (i.e. one cell per job) will return the same results as a run with every cell included? 

Is there any other part of the algorithm that would be affected by the set of input cells for a particular run?

Thanks!

**Comment by schel337** [comment]
Hi, sorry for the very late response. We've only recently started checking this page again.

And yes, having --lambda 0 means that the cells are completely independent so you can run them as different jobs and it will still return the same results. The only other part of the algorithm that would be affected would be microclustering (if enabled). Otherwise the algorithm is agnostic to other cells submitted in the same run.
