### ISSUE TITLE
Postprocessing in compassR vs manuscript

### ISSUE THREAD

**Issue by Hrovatin** [YosefLab/Compass#35]
In the manuscript the scores are said to be scaled with -log(1+score) while in compassR get_reaction_consistencies with -log2(score) followed by some filtering. Which should now be used?

**Comment by Hrovatin** [comment]
Also, I have one reaction that has scores below 0 R_NADtx_neg  from Recon3D on mouse.
![image](https://user-images.githubusercontent.com/47607471/115194665-0c107d80-a0ee-11eb-8c05-d1a71906f06d.png)

**Comment by schel337** [comment]
The compassR code is slated for substantial revisions. We recommend -log(1+x) currently, as used in the manuscript [here](https://www.biorxiv.org/content/biorxiv/early/2020/01/24/2020.01.23.912717/F13.large.jpg).

To scale the raw compass scores we subtracted the minimum entry in the matrix after taking -log(1+x) which makes them all non-negative. However, the reaction scores you are getting look unusually small if they are all on the order of 1e-12. In fact we removed rows in the matrix where the difference between maximum and minimum is less than 10^-3 for the manuscript. 

If you can give some more details on how you added Recon3 and what dataset you're running this on, I can definitely take a look at what's occurring.

**Comment by Hrovatin** [comment]
Thank you for the explanation.

I added this data  compass/Resources/Metabolic Models/RECON3/Recon3D.xml.gz and changed possible input options https://github.com/Hrovatin/Compass/commit/84ea2f9a6425673f44e8b89506d6adae8bbd4238

I get only one such reaction where score is below 0. Others look normal (top - scores, bottom - consistencies).
![slika](https://user-images.githubusercontent.com/47607471/115783476-3055ae00-a3bd-11eb-9d38-2151b50b2ad6.png)
![slika](https://user-images.githubusercontent.com/47607471/115783486-3481cb80-a3bd-11eb-94a6-36138f2bfa2b.png)
I have removed reactions with any score below 0 or all scores==0 for consistencies.

**Comment by schel337** [comment]
I tried replicating this on the example datasets and some others I have access to, but so far I've only gotten scores of 0 for R_NADtx_neg on mouse with the Recon3 model. My best guess is the negative penalties are due to the numerical precision of cplex, because the tolerance is 1e-12 or 1e-9 (depending on which algorithm is used) and the negative scores you are getting appear to be on that order of magnitude based on the graph. Given the numerical precision tolerances cplex uses, I think the scores can be treated as 0 if they are that small. 

To be able to replicate it, I would probably need to know the Cplex version and what dataset you are using. I assumed the dataset was on the examples that come with compass because you didn't specify, but if not I am not certain that I can replicate the negative scores.
