### ISSUE TITLE
Input data of compass

### ISSUE THREAD

**Issue by studymeow** [YosefLab/Compass#41]
Thank you for developing this tool. The documentation mentioned that we should use tpm, Just wondering if raw count data Also acceptable? Is there any particular reason that we must use tpm as input? Thank you! Looking forward to the advice!

**Comment by allonw** [comment]
Thanks for your interest in this work!

In the manuscript we analyze Smart-Seq, which is fully-transcript data and therefore the relevant unit was TPM. If you work with barcoded 3'/5' sequencing (e.g., 10x) then the equivalent would be working with CPMs. These units are computed from the raw counts and normalize for library depth that can otherwise bias results.

Is there a particular place in the docs that says TPM but doesn't mention CPM? We tried to consistently mention them together, please let us know if we missed a place and write just TPMs!

**Comment by DPLemonade** [comment]
Marking as resolved.
