### ISSUE TITLE
Problems running compass under different users in ubuntu

### ISSUE THREAD

**Issue by BKU-Technion** [YosefLab/Compass#42]
compass runs on ubuntu under the user it was installed.
When another user tries to run it the following error appears :
raceback (most recent call last):
  File "/home/guyho/.local/bin/compass", line 5, in <module>
    from compass.main import entry
ModuleNotFoundError: No module named 'compass'

**Comment by schel337** [comment]
I am not terribly experienced at wrestling with python configuration, but I am guessing this is because the Compass python module has somehow ended up installed under a user-specific PYTHONPATH for their site-packages while the bin is system wide. I would think the best way to fix this is to install Compass to a system-wide python installation if multiple users want to use it.   

Alternatively, you can add the folder where the Compass python module is installed to the PYTHONPATH variable (probably site-packages somewhere). For instance, I have Compass installed at /data/yosef/users/schel337/s137_lib/compass/__init__.py (found using import compass and compass.__file__) and my PYTHONPATH environment variable includes /data/yosef/users/schel337/s137_lib.

Hopefully that helps.

**Comment by BKU-Technion** [comment]
Thanks, that helped, pip installs packages locally by default.

**Comment by schel337** [comment]
Great, glad I could help!
