### ISSUE TITLE
install CPLEX in conda environment

### ISSUE THREAD

**Issue by Zymaniswenzai** [YosefLab/Compass#44]
Hi, Compass team!
I installed Compass in a conda environment and I need to install CPLEX in this environment, too.
So , What command should I replace `sudo` with?
```
cd ~
chmod +x cplex_studio129.linux-x86-64.bin
sudo ./cplex_studio129.linux-x86-64.bin
```
Thanks for any help.
JW

**Comment by schel337** [comment]
Hi JW,

You should be able to use just ./cplex_studio129.linux-x86-64.bin without sudo so long as you select an install directory that you have permissions for. 

Conda environments work well, just be careful that when [setting up Cplex's python API](https://www.ibm.com/docs/en/icos/20.1.0?topic=cplex-setting-up-python-api) that you have the conda environment activated, as otherwise Cplex will be installed to some other python distribution. That's messed up my installation once or twice.

**Comment by Zymaniswenzai** [comment]
Thanks, @schel337. It works well!
JW

**Comment by schel337** [comment]
Glad to help!
