### ISSUE TITLE
Correct workflow for running compass

### ISSUE THREAD

**Issue by Chengwei94** [YosefLab/Compass#59]
Hi there, how should I be running compass if I have 2 phenotype? 

Should I be running compass on each phenotype separately., then merge the results to compare? Another question is what if I have many different celltypes. Should I be running compass on each cluster separately, since I see that there is knn smoothing over the output matrix. Thanks!

**Comment by schel337** [comment]
For two phenotypes, the method we used in the paper was running Compass on both phenotypes combined with the knn smoothing, so gene expressions could potentially have been averaged across the phenotypes though in this case the phenotypes nearest neighbors tended to be of the same phenotype anyways. The averaging across k nearest neighbors helps mitigate dropout, which can results in lower predicted activity across all cells, but it could reduce the effect sizes across cell types.

I'll let Allon comment more on the tradeoffs of the smoothing as well.

**Comment by Chengwei94** [comment]
Hi @schel337 , 

thanks for the reply. 

> By default Compass does not smooth across samples though, in which case you can run the samples together or separately and get the same results.

I thought the default settings is 30 neighbor smoothing with 0.25 weight sharing though

**Comment by schel337** [comment]
The weight sharing parameter (--lambda which may not be the best name) is set to 0 by default, though if you want to enable it we suggest 0.25 or 0.2 as values.

**Comment by allonw** [comment]
Yes, I don't have much to add beyond Brandon's response. If you set lambda=0 (which is the default), namely no smoothing, then running them separately or together will produce the same results. 

In the Compass paper we used information sharing and ran the two phenotypes together because we were interested in the overlap and continuous gradient that existed between two seemingly disparate cell types. In other scenarios, where you have distinct phenotype and you're interested only in comparing between them, it may make more sense to run them separately, so that the kNN is computed separately on each phenotype and cells of phenotype A will not affect phenotype B.

**Comment by Chengwei94** [comment]
alright thanks! I think I skim through the docs and saw the 0,25 and mistakenly thought that it is 0.25 by default.
