### ISSUE TITLE
Using Compass with Bulk RNA-seq

### ISSUE THREAD

**Issue by gepmat** [YosefLab/Compass#69]
Hi, I would like to know if that is possible to use Compass with Bulk RNA-seq and not single cell only ?
Thanks,
Gepmat

**Comment by allonw** [comment]
Yes, as we write in the Discussion section of the paper, it's sound to run it on bulk data (just set the lambda parameter to 0 to prevent information sharing between samples). The only problem could be lack of statistical power since there are fewer observations (bulk samples rather than cells)

hope this helps!
